import { styled } from '@mui/material/styles';

interface CustomDivProps {
    display?: string,
    margin?: number | string,
    marginTop?: number | string,
    marginBottom?: number | string,
    marginLeft?: number | string,
    marginRight?: number | string,
    flex?: number | string,
    alignItems?: string,
    justifyContent?: string,
    padding?: string | number,
    cursor?: string,
    gap?: number | string,
    fontSize?: number | string,
    width?: number | string,
    height?: number | string,
    overflow?: string,
    backgroundColor?: string,
    border?: string,
    borderRadius?: number | string,
    flexDirection?: 'row' | 'row-reverse' | 'column' | 'column-reverse',
    backgroundImage?: string,
    backgroundRepeat?: string,
    backgroundSize?: string,
    minHeight?: number | string,
    minWidth?: number | string,
    flexWrap?: 'nowrap' | 'wrap' | 'wrap-reverse',
    whiteSpace?: string,
    wordWrap?: 'normal' | 'break-word',
    wordBreak?: 'normal' | 'break-all' | 'keep-all' | 'break-word',
    flexGrow?: number,
    textOverflow?: string,
    overflowX?: 'visible' | 'hidden' | 'clip' | 'scroll' | 'auto',
    overflowY?: 'visible' | 'hidden' | 'clip' | 'scroll' | 'auto',
    fontWeight? : string | number,
    alignSelf? : 'center',
    borderBottom? : string,
    color? : string,
    paddingTop? : string | number,
    paddingBottom? : string | number,
    borderTop? : string | number,
    maxWidth?: string | number,
    position?: 'static' | 'relative' | 'absolute' | 'fixed' | 'sticky',
    top? : string | number,
    right? : string | number,
    left? : string | number,
    bottom? : string | number,
    verticalAlign? : string | number,
    textAlign? : 'left' | 'right',
    transform? : string,
    paddingRight? : string | number,
}

const CustomDivStyle = styled("div")<CustomDivProps>(({ paddingBottom, display, margin, marginTop, marginBottom, marginLeft, marginRight, flex, alignItems, justifyContent, padding, cursor, gap, fontSize, width, height, overflow, backgroundColor, border, borderRadius, flexDirection, backgroundImage, backgroundRepeat, backgroundSize, minHeight, minWidth, flexWrap, whiteSpace, wordWrap, wordBreak, flexGrow, textOverflow, overflowX, overflowY, fontWeight, alignSelf, borderBottom, color, paddingTop, borderTop, maxWidth, position, top, right, left, bottom, verticalAlign, textAlign, transform, paddingRight}) => ({
    display: display,
    margin: margin,
    marginTop: marginTop,
    marginBottom: marginBottom,
    marginLeft: marginLeft,
    marginRight: marginRight,
    flex: flex,
    alignItems: alignItems,
    justifyContent: justifyContent,
    padding: padding,
    cursor: cursor,
    gap: gap,
    fontSize: fontSize,
    width: width,
    height: height,
    backgroundColor: backgroundColor,
    border: border,
    borderRadius: borderRadius,
    flexDirection: flexDirection,
    backgroundImage: backgroundImage,
    backgroundRepeat: backgroundRepeat,
    backgroundSize: backgroundSize,
    minHeight: minHeight,
    minWidth: minWidth,
    flexWrap: flexWrap,
    whiteSpace: whiteSpace,
    wordWrap: wordWrap,
    overflow: overflow,
    wordBreak: wordBreak,
    flexGrow: flexGrow,
    textOverflow: textOverflow,
    overflowX: overflowX,
    overflowY: overflowY,
    fontWeight : fontWeight,
    alignSelf : alignSelf,
    borderBottom: borderBottom,
    color: color,
    paddingTop : paddingTop,
    paddingBottom : paddingBottom,
    borderTop : borderTop,
    maxWidth: maxWidth,
    position: position,
    top: top,
    right: right,
    left: left,
    bottom: bottom,
    verticalAlign: verticalAlign,
    textAlign: textAlign,
    transform: transform,
    paddingRight: paddingRight
}));

export default CustomDivStyle;